version: 2

jobs:
  build:
    working_directory: ~/prefer.py

    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - run:
          name: Update Pip
          command: sudo pip install -U pip

      - run:
          name: Install virtualenv
          command: sudo pip install virtualenv

      - run:
          name: Create virtualenv
          command: virtualenv -p python3 .

      - run:
          name: Install Dependencies
          command: bin/python setup.py develop

      - run:
          name: Execute Unit Tests
          command: bin/python setup.py test

      - run:
          name: Install Coveralls
          command: bin/pip install coveralls

      - run:
          name: Upload Coverage Report
          command: bin/coveralls
